# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4f01cb49ebcffd299a256a09c2c4345a08244a681c04009bb86a2df4a380d20655ec5d6a081291b6969d910ad2682e497a7cade730c833696092db3ecb79ff3

test:
  secret_key_base: 620ae6d1d912a71ecd5705b523ecc185fd2156a052fcd0c12a5c8e22f1f604770546e2cc59cfae260cc06b3d99ec37573a8c6ef96b4e0ec4eb75deec6e6ad0a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
